spring.application.name=project_class11-1
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/project_class11_1_db
spring.datasource.username=leumsengheang
spring.datasource.password=30092007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

